# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisites_for_training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Ausbildungsvoraussetzungen',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('prerequisites', models.ManyToManyField(related_name='with_prerequisite', through='trainings.Prerequisites_for_training', to='trainings.Training', verbose_name='Voraussetzungen')),
            ],
            options={
                'verbose_name_plural': 'Ausbildungen',
            },
        ),
        migrations.AddField(
            model_name='Prerequisites_for_training',
            name='from_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_training', to='trainings.Training'),
        ),
        migrations.AddField(
            model_name='Prerequisites_for_training',
            name='to_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_training', to='trainings.Training'),
        ),
    ]
