# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possible_participates_in_trainingevent',
            name='first_register_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Erste Anmeldung'),
        ),
    ]
