# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisites_for_training',
            name='from_training',
        ),
        migrations.RemoveField(
            model_name='prerequisites_for_training',
            name='to_training',
        ),
        migrations.AddField(
            model_name='prerequisites_for_training',
            name='post_training',
            field=models.ForeignKey(default='t', on_delete=django.db.models.deletion.CASCADE, related_name='post_training', to='trainings.Training'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisites_for_training',
            name='pre_training',
            field=models.ForeignKey(default='t', on_delete=django.db.models.deletion.CASCADE, related_name='pre_training', to='trainings.Training'),
            preserve_default=False,
        ),
    ]
