# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participates_in_trainingevent',
            name='first_register_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Erste Anmeldung'),
        ),
        migrations.AddField(
            model_name='possible_participates_in_trainingevent',
            name='first_register_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Erste Anmeldung'),
        ),
    ]
