# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20180220_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prerequisites_for_training',
            options={'verbose_name': 'Ausbildungsvoraussetzung', 'verbose_name_plural': 'Ausbildungsvoraussetzungen'},
        ),
        migrations.AlterField(
            model_name='prerequisites_for_training',
            name='post_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_training', to='trainings.Training', verbose_name='F\xfcr Ausbildung'),
        ),
        migrations.AlterField(
            model_name='prerequisites_for_training',
            name='pre_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_training', to='trainings.Training', verbose_name='Voraussetzung'),
        ),
    ]
