# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20180319_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member_trainings',
            options={'verbose_name': 'Ausbildung von Mitglied', 'verbose_name_plural': 'Ausbildungen von Mitgliedern'},
        ),
        migrations.AddField(
            model_name='member_trainings',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
    ]
