# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0002_auto_20180213_1726'),
        ('trainings', '0004_auto_20180304_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participates_in_trainingevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Kommentar')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member')),
            ],
            options={
                'verbose_name': 'Teilnahme an Ausbildungstermin',
                'verbose_name_plural': 'Teilnahmen an Ausbildungstermin',
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField(verbose_name='Beginn')),
                ('event_end', models.DateTimeField(verbose_name='Ende')),
                ('max_member', models.IntegerField(verbose_name='Max. Teilnehmerzahl')),
                ('participants', models.ManyToManyField(through='trainings.Participates_in_trainingevent', to='member_administration.Member')),
                ('trainer', models.ManyToManyField(related_name='trainer', to='member_administration.Member')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.Training', verbose_name='Ausbildung')),
            ],
            options={
                'verbose_name': 'Ausbildungstermin',
                'verbose_name_plural': 'Ausbildungstermine',
            },
        ),
        migrations.AddField(
            model_name='participates_in_trainingevent',
            name='trainingevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingEvent'),
        ),
    ]
