# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20180305_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='direct_registration',
            field=models.BooleanField(default=True, verbose_name='Direktanmeldung m\xf6glich'),
        ),
    ]
