# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Handynummer')),
                ('adress_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stra\xdfe & Hnr.')),
                ('adress_plz', models.CharField(blank=True, max_length=6, null=True, verbose_name='PLZ')),
                ('adress_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('bw_join', models.DateField(blank=True, null=True, verbose_name='Bergwacht-Eintritt')),
                ('status', models.CharField(choices=[('AEK', 'Aktive Einsatzkraft'), ('ANW', 'Anw\xe4rter'), ('NEK', 'Nicht-aktive Einsatzkraft')], default='ANW', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'user__last_name'],
                'verbose_name_plural': 'Mitglieder',
            },
        ),
        migrations.CreateModel(
            name='MemberHasQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='memberhasqualification',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Qualification'),
        ),
    ]
