# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberhasqualification',
            options={'verbose_name_plural': 'Qualifikationen von Mitgliedern'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name_plural': 'Qualifikation'},
        ),
        migrations.AlterField(
            model_name='memberhasqualification',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member', verbose_name='Mitglied'),
        ),
        migrations.AlterField(
            model_name='memberhasqualification',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Qualification', verbose_name='Qualifikation'),
        ),
    ]
