# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0002_auto_20180213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Trupps',
            },
        ),
        migrations.CreateModel(
            name='Members_in_Dutygroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.DutyGroup', verbose_name='Trupp')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name_plural': 'Truppmitgliedschaft',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='dutygroups',
            field=models.ManyToManyField(through='member_administration.Members_in_Dutygroup', to='member_administration.DutyGroup'),
        ),
    ]
