# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20180320_1734'),
        ('member_administration', '0004_auto_20180318_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainings',
            field=models.ManyToManyField(related_name='trainings', through='trainings.Member_Trainings', to='trainings.Training'),
        ),
    ]
