# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0005_member_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Portrait'),
        ),
    ]
