# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0002_auto_20180213_1726'),
        ('trainings', '0005_auto_20180304_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possible_participates_in_trainingevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Kommentar')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member')),
            ],
            options={
                'verbose_name': 'M\xf6gliche Teilnahme an Ausbildungstermin',
                'verbose_name_plural': 'M\xf6gliche Teilnahmen an Ausbildungstermin',
            },
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='id',
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='training_event_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='trainings.Participates_in_trainingevent', to='member_administration.Member'),
        ),
        migrations.AddField(
            model_name='possible_participates_in_trainingevent',
            name='trainingevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingEvent'),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='possible_participants',
            field=models.ManyToManyField(related_name='possible_participants', through='trainings.Possible_participates_in_trainingevent', to='member_administration.Member'),
        ),
    ]
