# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('duty_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Dienstnummer')),
                ('duty_start', models.DateTimeField(verbose_name='Dienstbeginn')),
                ('duty_end', models.DateTimeField(verbose_name='Dienstende')),
            ],
            options={
                'verbose_name_plural': 'Dienste',
            },
        ),
        migrations.CreateModel(
            name='Dutyarea',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='duty_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_scheduler.Dutyarea', verbose_name='Dienstgebiet'),
        ),
    ]
