# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_administration', '0002_auto_20180213_1726'),
        ('duty_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes_part_in_duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField(verbose_name='Von')),
                ('to_time', models.DateTimeField(verbose_name='Bis')),
                ('function', models.CharField(blank=True, max_length=3, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Kommentar')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty_scheduler.Duty')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_administration.Member')),
            ],
            options={
                'verbose_name_plural': 'Dienstteilnahme',
            },
        ),
        migrations.AddField(
            model_name='duty',
            name='mitglieder',
            field=models.ManyToManyField(through='duty_scheduler.Takes_part_in_duty', to='member_administration.Member'),
        ),
    ]
