# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty_scheduler', '0002_auto_20180214_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='mitglieder',
            new_name='members',
        ),
    ]
