# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty_scheduler', '0003_auto_20180214_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutycategory',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='duty',
            name='minaek',
            field=models.IntegerField(blank=True, null=True, verbose_name='Geforderte AEK'),
        ),
        migrations.AddField(
            model_name='duty',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='duty_scheduler.Dutycategory'),
        ),
    ]
