# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty_scheduler', '0004_auto_20180214_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutyrole',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='takes_part_in_duty',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duty_scheduler.Dutyrole'),
        ),
    ]
