# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_scheduler', '0005_auto_20180219_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name': 'Dienste', 'verbose_name_plural': 'Dienste'},
        ),
        migrations.AlterModelOptions(
            name='dutyarea',
            options={'verbose_name': 'Dienstgebiet', 'verbose_name_plural': 'Dienstgebiete'},
        ),
        migrations.AlterModelOptions(
            name='dutycategory',
            options={'verbose_name': 'Dienstkategorie', 'verbose_name_plural': 'Dienstkategorien'},
        ),
        migrations.AlterModelOptions(
            name='dutyrole',
            options={'verbose_name': 'Dienstrolle', 'verbose_name_plural': 'Dienstrollen'},
        ),
        migrations.AlterModelOptions(
            name='takes_part_in_duty',
            options={'verbose_name': 'Dienstteilnahme', 'verbose_name_plural': 'Dienstteilnahmen'},
        ),
        migrations.AddField(
            model_name='dutyrole',
            name='shortname',
            field=models.CharField(default='X', max_length=10, verbose_name='K\xfcrzel'),
            preserve_default=False,
        ),
    ]
