# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_scheduler', '0008_auto_20180304_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyarea',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
    ]
